{% set name = "antimeridian" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/antimeridian-{{ version }}.tar.gz
  sha256: 00c0028815fda03d0e95d5cf102c2d427264ebecd9a90f97d2271e22ba239653

build:
  entry_points:
    - antimeridian = antimeridian._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - shapely >=2.0
    - click >=8.1,=8.*

test:
  imports:
    - antimeridian
  commands:
    - pip check
    - antimeridian --help
  requires:
    - pip

about:
  home: https://github.com/gadomski/antimeridian
  summary: Fix GeoJSON geometries that cross the antimeridian
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://antimeridian.readthedocs.io
  dev_url: https://github.com/gadomski/antimeridian

extra:
  recipe-maintainers:
    - gadomski
