{% set name = "antimeridian" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/antimeridian-{{ version }}.tar.gz
  sha256: fde0134e6799676ec68765d3e588f5f32cabd4041b1f969b923758d0a6cd0c7f

build:
  entry_points:
    - antimeridian = antimeridian._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - shapely >=2.0
    - numpy >=1.22.4
    - click >=8.1,=8.*

test:
  imports:
    - antimeridian
  commands:
    - pip check
    - antimeridian --help
  requires:
    - pip

about:
  home: https://github.com/gadomski/antimeridian
  summary: Fix GeoJSON geometries that cross the 180th meridian
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://antimeridian.readthedocs.io
  dev_url: https://github.com/gadomski/antimeridian

extra:
  recipe-maintainers:
    - gadomski
