{% set name = "antimeridian" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/antimeridian-{{ version }}.tar.gz
  sha256: 96309322056c69189d44a3695f266b40362a7d3aa591198d592562deb34dd062

build:
  entry_points:
    - antimeridian = antimeridian._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - shapely >=2.0
    - numpy >=1.22.4
    - click >=8.1,=8.*

test:
  imports:
    - antimeridian
  commands:
    - pip check
    - antimeridian --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gadomski/antimeridian
  summary:  Correct GeoJSON geometries that cross the 180th meridian 
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://www.gadom.ski/antimeridian/latest/
  dev_url: https://github.com/gadomski/antimeridian

extra:
  recipe-maintainers:
    - gadomski
